[package]
name = "rusterizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.22.0"
gltf = {version="1.0.0", features = ["import", "names"] }
minifb = "0.23.0"
stb_image = "0.2.4"
